openapi: 3.0.0
info:
  title: Authentication
  description: |
    Turn uses JSON Web Tokens (JWT) keys to allow access to the API. Before making any requests to the API you must request a token. Please request a token by contacting your sales representative.
    # 
    All API requests to the Turn API must include the JWT in an Authorization header. The format of the header is described below:


        Authorization: Bearer <jwt_token>

    Where *Authorization* is the header name, and *Bearer jwt_token* is the header value.

    > You must replace jwt token with your personal API key.
  contact: {}
  version: '1.0'
servers:
  - url: 'https://api.turn.ai/v1'
    variables: {}
paths:
  /public_api/me:
    get:
      tags:
        - Authentication
      summary: My Account
      description: Issue a simple request to validate your JWT Token. This endpoint will give back your correct Account name if the provided token is valid. In no Authorization header is present a 401 http response will be issued. If the token is invalid a 400 http response will be issued.
      operationId: /public_api/me
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                name: ACME
        '400':
          description: BAD REQUEST
          content:
            application/json:
              example:
                code: invalid_header
                description: Unable to parse authentication token
        '401':
          description: UNAUTHORIZED
          content:
            application/json:
              example:
                code: authorization_header_missing
                description: Authorization header is expected
      deprecated: false
components:
  schemas:
    200Sucess:
      title: 200Sucess
      required:
        - name
      type: object
      properties:
        name:
          type: string
      example:
        name: ACME
      x-internal: true
    400InvalidToken1:
      title: 400InvalidToken1
      required:
        - code
        - description
      type: object
      properties:
        code:
          type: string
        description:
          type: string
      example:
        code: invalid_header
        description: Unable to parse authentication token
      x-internal: true
    401NoTokenProvided1:
      title: 401NoTokenProvided1
      required:
        - code
        - description
      type: object
      properties:
        code:
          type: string
        description:
          type: string
      example:
        code: authorization_header_missing
        description: Authorization header is expected
      x-internal: true
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
  - httpBearer: []
tags:
  - name: Authentication
